### PR TITLE
Update index.jsx

### PR DESCRIPTION
**Pull request by ghost**
*Edit

### CODE REVIEW

**Comment by SheepTester** [comment]
??? Why "puny"?

**Comment by ghost** [comment]
Just a test.

**Comment by ghost** [comment]
Seriously.

**Comment by SheepTester** [comment]
I don't see why I should merge this, so I shall close this PR

**Comment by ghost** [comment]
I’m not really that used to github so I don’t know what merge is.

**Comment by SheepTester** [comment]
Ah, pull requests are for when you want to have your changes merged with the original code; presumably GitHub assumed you intended on changing the original code here, so it suggested to make a pull request when you made a change on your fork

**Pull request closed without merging**
